### PR TITLE
Provide instances for bitvec

### LINKED ISSUE #20: Instances for Vector Bit
Would it be appropriate to prepare a PR, adding `Rank{0,1}` and `Select{0,1}` instances for `Vector Data.Bit.Bit` from [`bitvec`](http://hackage.haskell.org/package/bitvec) package? I intend to use [`nthBitIndex`](http://hackage.haskell.org/package/bitvec-1.0.2.0/docs/Data-Bit.html#v:nthBitIndex) and [`countBits`](http://hackage.haskell.org/package/bitvec-1.0.2.0/docs/Data-Bit.html#v:countBits).

### PR DESCRIPTION
**Pull request by Bodigrim**
Closes #20.

Tests can be found in https://github.com/Bodigrim/hw-rankselect-base/tree/tests, but I do not submit it for merge because of orphan instances.

### CODE REVIEW

**Comment by Bodigrim** [comment]
How does it look, @newhoggy?

**Comment by newhoggy** [comment]
Sorry, I've been pre-occupied with other things.  Looking at this now.

**Comment by newhoggy** [comment]
Do you by any chance know what this comment in the `bitvec` docs is referring to?

```
This module exposes an interface with thread-unsafe writes and flips. Consider using Data.Bit.ThreadSafe, which is thread-safe, but slower (up to 20%).
```

**Comment by Bodigrim** [comment]
Sure, most of the current incarnation of `bitvec` is written by me.

https://github.com/Bodigrim/bitvec/blob/master/README.md#thread-safety gives a bit more details:
> * `Data.Bit` is faster, but writes and flips are thread-unsafe. This is because naive updates are not atomic: read the whole word from memory, then modify a bit, then write the whole word back.
> * `Data.Bit.ThreadSafe` is slower (up to 20%), but writes and flips are thread-safe.

If multiple threads concurrently write neighbouring bits in the same word, they may end up with inconsistent states, effectively losing the work of one of the threads:

```
thread1: x <- arr[0]
thread2: y <- arr[0]
thread1: x |= 1<<16
thread2: y |= 1<<24
thread1: arr[0] <- x 
thread2: arr[0] <- y
```

In multithreaded enviroment we must ensure that threads access a mutable vector in turns:

```
thread1: x <- arr[0]
thread1: x |= 1<<16
thread1: arr[0] <- x 
thread2: y <- arr[0]
thread2: y |= 1<<24
thread2: arr[0] <- y
```

`Data.Bit.ThreadSafe` ensures this restriction, using atomic locks. Unfortunately, there is an associated performance cost, non-negligible for some applications. That is why `bitvec` provides both `Data.Bit` and `Data.Bit.ThreadSafe`.

**Comment by newhoggy** [comment]
Thanks for the explanation.

**Comment by newhoggy** [comment]
Would you be able to add property tests to verify that the indexing and endian-ness is the same as rank/select for say `[Bool]` or `Vector`?

**Comment by Bodigrim** [comment]
As mentioned above, I can add the tests (https://github.com/Bodigrim/hw-rankselect-base/commit/b0c6b5c15e0034b4bb9dfa7d83dba921592b7772), but they involve a (rather hastily written) orphan `instance BitRead (DVU.Vector Bit.Bit)`. Is it OK?

Or I can take a long way and add these instances to `hw-bits`, if you are happy to accept such contributions.

**Comment by newhoggy** [comment]
Please add the instance to `hw-bits`. 😁

**Comment by Bodigrim** [comment]
I have added some tests, please re-review.

**Comment by newhoggy** [comment]
Nice! Thanks!

**Pull request merged**
